// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByUoTq31m6GPg3QKFerumKXf0CgzCTaKg',
    appId: '1:388493344657:web:5e5f5cc1408ec63dace430',
    messagingSenderId: '388493344657',
    projectId: 'loginpage-27a12',
    authDomain: 'loginpage-27a12.firebaseapp.com',
    storageBucket: 'loginpage-27a12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOhdll8sQ5MPjt6iC94-zrtcD0-r-5_RQ',
    appId: '1:388493344657:android:974a3a6b936b4251ace430',
    messagingSenderId: '388493344657',
    projectId: 'loginpage-27a12',
    storageBucket: 'loginpage-27a12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKHnlUHSQXldUn5P6XiSX0ERfBV407kYE',
    appId: '1:388493344657:ios:d477cdbee274384eace430',
    messagingSenderId: '388493344657',
    projectId: 'loginpage-27a12',
    storageBucket: 'loginpage-27a12.appspot.com',
    androidClientId: '388493344657-vnjpvpk2s5rtokdlfmf5gcf8s289mf0j.apps.googleusercontent.com',
    iosClientId: '388493344657-ovlsk6e9fckfrgmp9324c1dbavc8j8oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.menufy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKHnlUHSQXldUn5P6XiSX0ERfBV407kYE',
    appId: '1:388493344657:ios:d477cdbee274384eace430',
    messagingSenderId: '388493344657',
    projectId: 'loginpage-27a12',
    storageBucket: 'loginpage-27a12.appspot.com',
    androidClientId: '388493344657-vnjpvpk2s5rtokdlfmf5gcf8s289mf0j.apps.googleusercontent.com',
    iosClientId: '388493344657-ovlsk6e9fckfrgmp9324c1dbavc8j8oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.menufy',
  );
}
